proxy:
  uri: https://www.watchseries1.video/all-series
  select: li.list-group-item>a
  attribute: href

spring:
  main:
    cloud-platform: none
    lazy-initialization: true
    web-application-type: reactive
  codec:
    max-in-memory-size: 1MB
